#!/bin/sh

uci set fstab.@global[0].anon_mount=1
uci commit fstab

uci set firewall.@defaults[0].flow_offloading=1
uci set firewall.@defaults[0].flow_offloading_hw=1
uci set firewall.@defaults[0].fullcone=2
uci commit firewall

uci set upnpd.config.enabled=1
uci commit upnpd

uci set wireless.@wifi-device[0].channel=auto
uci set wireless.@wifi-device[1].channel=auto
uci set wireless.@wifi-device[1].htmode=HE160
uci set wireless.@wifi-iface[0].skip_inactivity_poll=1
uci set wireless.@wifi-iface[1].skip_inactivity_poll=1
uci set wireless.@wifi-iface[0].disassoc_low_ack=0
uci set wireless.@wifi-iface[1].disassoc_low_ack=0
wireless.wifinet0.wpa_master_rekey='0'
wireless.wifinet0.disassoc_low_ack='0'
wireless.wifinet0.key='bettyboop'
wireless.wifinet0.ieee80211r='1'
wireless.wifinet0.ft_over_ds='1'
wireless.wifinet0.ft_psk_generate_local='1'
wireless.wifinet1=wifi-iface
wireless.wifinet1.device='radio1'
wireless.wifinet1.network='lan'
wireless.wifinet1.mode='ap'
wireless.wifinet1.ssid='Tenda_4BA290_5G'
wireless.wifinet1.encryption='psk-mixed'
wireless.wifinet1.skip_inactivity_poll='1'
wireless.wifinet1.wpa_group_rekey='0'
wireless.wifinet1.wpa_pair_rekey='0'
wireless.wifinet1.wpa_master_rekey='0'
wireless.wifinet1.disassoc_low_ack='0'
wireless.wifinet1.key='bettyboop'
wireless.wifinet1.ieee80211r='1'
wireless.wifinet1.ft_over_ds='1'
wireless.wifinet1.ft_psk_generate_local='1
uci commit wireless

/etc/init.d/mtd-rw start

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm

#ln -sf /sbin/ip /usr/bin/ip

sed -i '/openwrt_luci/ { s/snapshots/releases\/18.06.9/g; }'  /etc/opkg/distfeeds.conf

#sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
#echo 'iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
#echo 'iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user

#echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
#echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='R23.8.23'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt '" >> /etc/openwrt_release

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
